---
title: "UKE40"
format: html
editor: visual
---

```{r}
#| message: FALSE
#| label: setup
library(tidyverse)
library(vtable)
library(flextable)
```

##EDA

```{r}
my_heights <- modelr:: heights
```

```{r}
# NAs in my_heights?
my_heights %>% 
  apply(MARGIN = 2, FUN = is.na) %>% 
  apply(MARGIN = 2, FUN = sum) |> 
  print(width = 40)
```

samme svar:

```{r}
# NAs in my_heights?
my_heights %>% 
  is.na() %>% 
  apply(MARGIN = 2, FUN = sum)  |> 
  print(width = 40)
```

```{r}
# package vtable 
# must be installed
my_heights %>% 
  select(
    -marital, 
    -sex
    ) %>% 
  # . to stop RStudio 
  # complaining about 
  # no data
  vtable::st(data = ., out = "return") |> 
  as_flextable()
```

Gjør den litt finere med flextable():

```{r}
# package vtable must 
# be installed
my_heights %>% 
  select(marital, sex) %>% 
  vtable::st(
    data = ., 
    out = "return"
    ) |> 
  as_flextable()
```

Det som er under er det du må skrive når du skal ha typ tekst i bilde ditt, eller om du skal ha en figur, da velger du den som passer.
Typ skal du ha en tabell skrift så skriver du eks:

#\| label: tbl-DescStat

```{r}
#| label: tbl-
#| label: fig-
```

## Uke 41

```{r}
# package vtable 
# must be installed
tab1 <- my_heights |>  
select(-marital, -sex) |> 

vtable::st(out = "return") |> 
as_flextable(show_coltype = FALSE, max_rows = 20)|> 

line_spacing(space = 0,3) |> 
autofit() |>     delete_part("footer") |> 
theme_booktabs() |> 
bg(i = 6, j = c(5, 8), bg = "purple")

tab1
```

```{r}
tab1 |> 
bg(i = 3, j = c(2, 4), bg = "pink")
```
